# Generated by Django 5.0.3 on 2024-03-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startingblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Welcome to Blogsinzzz', max_length=255),
        ),
    ]
